name: Build and Upload APK to Diawi


on:
  push:
    branches:
      - dev  # Change to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # Cache Gradle dependencies (optional for faster builds)
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission for Gradle wrapper
      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      # Build APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Upload APK to Diawi and get the link
      - name: Upload APK to Diawi
        id: upload_diawi
        run: |
          DIAWI_API_KEY="${{ secrets.DIAWI_API_KEY }}"
          APK_PATH="app/build/outputs/apk/release/app-release.apk"

          # Upload APK using curl and save the response
          DIAWI_RESPONSE=$(curl -X POST \
            -F "file=@${APK_PATH}" \
            -F "token=${DIAWI_API_KEY}" \
            -F "install=true" \
            https://upload.diawi.com/)
          
          # Extract the link from the response using jq
          DIAWI_LINK=$(echo $DIAWI_RESPONSE | jq -r .link)
          
          # Set the link as an environment variable
          echo "DIAWI_LINK=${DIAWI_LINK}" >> $GITHUB_ENV

      # Show the Diawi link
      - name: Show Diawi link
        run: |
          echo "APK is available at: ${{ env.DIAWI_LINK }}"
